"""tables reduce

Revision ID: 99f3b15f49ab
Revises: 0f09ea8fd60b
Create Date: 2017-08-05 03:51:38.765471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f3b15f49ab'
down_revision = '0f09ea8fd60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_default', table_name='roles')
    op.drop_column('roles', 'default')
    op.drop_column('roles', 'permissions')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    # ### end Alembic commands ###
